### PR TITLE
fix Signal issue with Sanic 21.9

### LINKED ISSUE #61: Problem with sanic>21.6
Hey, 

Thanks for the great library!

Seems like there is an error on ``sanic > 21.6``. The failure I see looks like that:

```
ERROR    sanic.error:http_protocol.py:110 protocol.connection_task uncaught
Traceback (most recent call last):
  File "/Users/rmk/projects/ets-labs/python-dependency-injector/venv/lib/python3.10/site-packages/sanic/server/protocols/http_protocol.py", line 101, in connection_task
    await self.app.dispatch(
  File "/Users/rmk/projects/ets-labs/python-dependency-injector/venv/lib/python3.10/site-packages/sanic/signals.py", line 163, in dispatch
    return await dispatch
  File "/Users/rmk/projects/ets-labs/python-dependency-injector/venv/lib/python3.10/site-packages/sanic/signals.py", line 111, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/Users/rmk/projects/ets-labs/python-dependency-injector/venv/lib/python3.10/site-packages/sanic/signals.py", line 73, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
ERROR    asyncio:plugin.py:76 Task exception was never retrieved
future: <Task finished name='Task-19' coro=<HttpProtocol.connection_task() done, defined at /Users/rmk/projects/ets-labs/python-dependency-injector/venv/lib/python3.10/site-packages/sanic/server/protocols/http_protocol.py:92> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/Users/rmk/projects/ets-labs/python-dependency-injector/venv/lib/python3.10/site-packages/sanic/server/protocols/http_protocol.py", line 130, in connection_task
    await self.app.dispatch(
  File "/Users/rmk/projects/ets-labs/python-dependency-injector/venv/lib/python3.10/site-packages/sanic/signals.py", line 163, in dispatch
    return await dispatch
  File "/Users/rmk/projects/ets-labs/python-dependency-injector/venv/lib/python3.10/site-packages/sanic/signals.py", line 111, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/Users/rmk/projects/ets-labs/python-dependency-injector/venv/lib/python3.10/site-packages/sanic/signals.py", line 73, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
```

The failure occurs all the time, but if you need an example, take a look at: https://github.com/ets-labs/python-dependency-injector/tree/master/examples/miniapps/sanic

Thanks,
Roman

### PR DESCRIPTION
**Pull request by wochinge**
**Proposed Changes**
- fix https://github.com/yunstanford/pytest-sanic/issues/61

### CODE REVIEW

**Comment by wochinge** [comment]
Should I also update `poetry.lock`? We might also wanna double check if this actually works with older Sanic versions

**Comment by indam23** [comment]
I've ported this fix to https://github.com/yunstanford/pytest-sanic/pull/66 and added the changes mentioned in the issue

**Comment by wochinge** [comment]
@ancalita @melindaloubser1 there is also an official test library for Sanic (https://sanic.dev/en/plugins/sanic-testing/getting-started.html) which I’d recommend to use instead of pytest-sanic. I switched out the Rasa X code with that one and it was relatively straight forward if I remember correctly

**Comment by indam23** [comment]
Thanks for the tip @wochinge  🙏

**Comment by ottonemo** [comment]
@yunstanford do you think this can be merged? This prevents people from using current sanic versions :)

**Pull request closed without merging**
