### PR TITLE
Fix issue preventing use of websockets==6.0

### PR DESCRIPTION
**Pull request by hairychris**
Could you please rebuild the wheels?

### CODE REVIEW

**Comment by hairychris** [comment]
Actually I was right the first time, this does fix it.

**Comment by hairychris** [comment]
Hmm, seems to fail on test_fixture_test_client_passing_headers claiming that the output of request.json() is a list not a dictionary.

**Comment by yunstanford** [comment]
hey, the test task in ubuild.py is actually only used for pytestsanic unit tests. Also note, It has nothing to do with its wheel. Websockets is not a direct dependency of this repo. It's actually Sanic using it. The dependencies of this repo is listed in setup.py. 

What exactly are you looking for ?

**Comment by yunstanford** [comment]
Also checkout Sanic dependency versions here: 
https://github.com/channelcat/sanic/blob/master/setup.py

**Comment by hairychris** [comment]
Sorry I believe this was an issue with my setup and Pipenv.

**Pull request closed without merging**
