### PR TITLE
Remove conflicting tmpdir fixture. Fixes #7

### LINKED ISSUE #7: Remove tmpdir fixture
The tmpdir fixture in pytest-sanic conflicts (and has different semantics) than the tmpdir fixture available in standard pytest. Please remove it

### PR DESCRIPTION
**Pull request by cybergrind**
pytest now has its own `tmpdir` fixture with better interface than string type provides https://docs.pytest.org/en/latest/tmpdir.html#the-tmpdir-fixture

### CODE REVIEW

**Comment by yunstanford** [comment]
@cybergrind Thanks for your PR. Can you also update the version in `__init__.py` very quick ?https://github.com/yunstanford/pytest-sanic/blob/master/pytest_sanic/__init__.py

**Comment by cybergrind** [comment]
@yunstanford sure, my fault. Update and rebased

**Comment by cybergrind** [comment]
@yunstanford could you please also update pypi version to 0.1.5? ty

**Comment by yunstanford** [comment]
@cybergrind done.

**Pull request merged**
